functional:
  - Пользователь может соревноваться с ботами 
  - Пользователь может соревноваться с другим пользователем по ссылке
  - Пользователю доступны рейтинги
  - Пользователь может видеть решение задач другим пользователем онлайн
  - Пользователь может настраивать сложность, время и тип соревнований
  - Пользователь может выбирать язык программирования для решения задач
  - Пользователь может авторизовываться и регистрироваться разными способами на сайт
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Должно быть форматирование ЯП
